### ISSUE TITLE
Please bring back the blue.

### ISSUE THREAD

**Issue by ghost** [11011110/blog#1]
Your blog has changed from blue to white. I liked it better blue.

**Comment by 11011110** [comment]
It's definitely something I've already considered doing (and haven't rejected). If I bring it back, it would only be for the front page (and all posts list), not for the individual postings — too many of them have image formatting that assumes the background is white (as it was for individual postings on LJ).

**Comment by ghost** [comment]
This issue has been resolved by the commit a43063f23f7580c63854f81e5c86e7daa6428908.

I like the blue.
